title: Herbert Rocha
description: My Personal Web Site
author: Herbert Rocha
logo: /static/img/avatar.jpg
github: https://github.com/hbgit
about: Research Professor

baseurl: "https://hbgit.github.io/"
url: ""

allowsearch: true

disqus_shortname: hbgit.disqus.com
google_analytics: 

share:
  twitter_username: \@herberthb12
  fb_appid: herbert.rocha.54


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
